server:
  port: 9099 #端口
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://111.231.50.113:3306/job_time?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: manager
      initialSize: 1  #初始化大小
      minIdle: 1  #空闲连接池的大小
      maxActive: 50 #最大激活数量
  servlet:
    multipart:
      max-file-size: 50MB #单个文件上传大小限制
      max-request-size: 500MB #单次请求上传文件大小限制
#MyBatis配置文件
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
#日志打印SQL
logging:
  level:
     com.job: debug  #日志级别
  config: classpath:logback.xml  #加载指定日志文件
system:
  domainName: http://127.0.0.1 #域名
  picPath: /opt/tomcat/webapps/mes  #上传图片路径
swagger:
  enable: true #是否开启swagger

fileSavePath: C:/photo/

resourcePath: /resource

appId: 1400111151
appKey: e1984a557f3ed83fb554ed1f76fe92cb
templateId: 153000
smsSign: "小蜜蜂一站式平台"

wx:
  notifyUrl: http://localhost/wx/notify #微信回调地址
  appId: wxc8e1a3732b85cd01
  appKey: a9eb523e05e230c6443a2526f8ccb511
zfb:
  returnUrl: http://www.xxx.com/alipay/return_url.do  #支付宝回调页面
  notifyUrl: http://localhost/notify                  #支付宝回调地址
  url: https://openapi.alipaydev.com/gateway.do       #支付宝的网关地址
  appId: 2016101700706212
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSu40/0/tSHgrQc15pJp0uhYCSuhpRN1leONyU/HtU9r46xO72Ipt6xJ+cr7sYlVf4yroALydc/syQV8eGIYnSUX+r50hbYm3zu/GUCObiOhlUzToxuQdEZ7K5dgifkGmL26qElSaTn+apr8u2BBLhqQ9z8rwiFDVlAM3+/XNCq94owhVcXl+HntDmHZmCti9voJMJajY1OuYbuTZ9tBkmPRbu+t5OVV7co3TmeDEmjVXW9KJhpNCbvZRM5X1GhYTUYz08dwZIxE86nkcoP8X38qP0F9oZrvJGGaWNHEtIh1fFDdtfvlQtJ6gPA8NP58rKHAJLvn2frmSeJa1HheVNAgMBAAECggEAV5diIGIYutJ4PitAhqCoX+cN84jowOa7kIV9F+sIbJXGxSpeQ8ww6D6L0WsN0wUDuN673fRIGTl5QAlGcAmBTm2cOzAbf4HohQECmw4dVZq9GGRSgvAjKHCGvjN5vlbkyrpctjybBLEFbvIkNwmDg/X55YtXRzitDxhF4BvIPFmSDdAKrZT0jxlLrn0oP0I/jX9NzNzVM0h/DD8m1osaNzM/IvXCUdSMJUcx/HIChIjVNztyblYp2DOKP1Sv+5uuMdV3h+RygU7JSQlcoQvs+7IIhqf03dlQbetzWIAa/eyzfYjgkUAw7wImhaN0UUrR/qcmE6wt8A7ehc/ibBZJAQKBgQD4HCkE5/SRDJPhRnBi4lo3xuUHK2jxuEayJJdU++GaV0woEIiJQyJEi4qfjMiu4dX35i2p4c8MV1MT3ZI9GEMdk5kZ2pIt7oKJ+shAWxB8HWJnTA/ysQcvtR8YCUgFfGiSzi7SL9LDE+/mEX3g9PWduZeUpSxQ1Xl2EWsu7JUGYQKBgQCXZhaHV4g4b03stOlo9RHjYCHGjKZ+bLbweC8/vMfgaUUK8JRnL3VxOv82ngOj/aFofQrN4CPsMbEyODwalDzQ/P/xsbn0n2bNt82CSk71oGj5Q/m/I/w5Mb5UeyE3S+SnFaZrcg7qDtHFk96hFYzEeXuW8t46RKi2CNG8KqTubQKBgQC5OlTJS95C96/jS/IVcMVHxN4xNxBW/WsSDc1I7e7kie3aL1WvnAYWRFMOgE1GemWCeD55CJLJtNvaBd3qbJWWnB19trbRQbIFDsu3eATblBhl49w4JD+oN0Dqcetp5RIxH2rHElr3toewLDjc3CQOR4NJvvJRur2+Do0FcCxloQKBgCb2bOHT0wjDDEjYniEWwM3FVavlUovCqqnkJDTA/qdwMAaKt4Z+njjPuBJ0Q/eWNE3RsFAfWN9WQoXsFvu4HpaiJbQryvF7fFeA7/CR8xQffiR4K/PW7PhDJvpS3c9/Ro8BcVzBc7kkqzOvxGGsTBfcM8Q7KJnSRaDjUCaeyudZAoGAGxLHVekCe4C9awDGvJhNw3PsfAM1eCWwX5LZQ3JQZbv7J6jwipLCaMvwxdItG6hNlW3fKpxlsN0YakzU2qwsaPUfzaUjFYq2bExQzG9jWP4MI/2Vs6/4Uy0YoXdVY/XnOxGOVd+OJ7WO/DwCt0MJ69IADpIlOgEVIXcJxbLd4Rc=
  appPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkruNP9P7Uh4K0HNeaSadLoWAkroaUTdZXjjclPx7VPa+OsTu9iKbesSfnK+7GJVX+Mq6AC8nXP7MkFfHhiGJ0lF/q+dIW2Jt87vxlAjm4joZVM06MbkHRGeyuXYIn5Bpi9uqhJUmk5/mqa/LtgQS4akPc/K8IhQ1ZQDN/v1zQqveKMIVXF5fh57Q5h2ZgrYvb6CTCWo2NTrmG7k2fbQZJj0W7vreTlVe3KN05ngxJo1V1vSiYaTQm72UTOV9RoWE1GM9PHcGSMRPOp5HKD/F9/Kj9BfaGa7yRhmljRxLSIdXxQ3bX75ULSeoDwPDT+fKyhwCS759n65kniWtR4XlTQIDAQAB
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmDGgvK0cG0MXqqVqWG9WnSeouwmBqA8frf0GBAWviEHM9mG5SDZ0uJmmPVX3yAvD5bofm9gJl2+4s3RInxMJctgDVdSZUSZSwIo0gLPuxqDpIVOQCwn5y18XWbLCjqnK5D0oWI5I77P6yVDpyLV8Px/5SO4f2wxuA3M56JpdhPoePHecePzjGy4PLnR5DfJG+Yd8MWdpps+5Jn1PGBZjK3qDoThG8coQtqtq/g9INBFVajvZ/g6odkeP8uoE7PKv1h3ut44xKjeO9TPuvQG5izVAbRunKWcqoF6NJZfRDe8hEVNKZv4f8ag2aMIEyCN075rwnZ0fA06fSbXpc62iYQIDAQAB